### ISSUE TITLE
TS Bindings: Upgrade Typescript to latest

### ISSUE THREAD

**Issue by piyalbasu** [stellar/stellar-cli#1155]
Upgrade the packaged Typescript version to the latest.
https://www.npmjs.com/package/typescript?activeTab=versions

**Comment by janewang** [comment]
Maybe we could add [dependbot](https://github.com/dependabot) in this repo.

**Comment by damingerdai** [comment]
but i think renovate is better

**Comment by Joy-Adah** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stellar-cli).

### My background and how it can be leveraged
Hi. My name is Joy and i am a web3 developer and open source contributor.

### How I plan on tackling this issue
I plan to solve this by reviewing carefully the existing typescript version, ensuring its compatibility and then upgrading it. I will also test the changes thoroughly to avoid breaking existing functions and also add the changes to the ReadME.

**Comment by Dprof-in-tech** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stellar-cli).

### My background and how it can be leveraged
Hello, i am Dprof-in-tech, an experienced Full Stack Blockchain Developer and  I am excited to contribute my skills to the this project in this ODHACK 8. With a strong background in Next.js, TypeScript, JavaScript, React, Node.js, Rust and Cairo, I've honed my technical skills across the blockchain development landscape.
My journey with OnlyDust began at Edition 2, and I've since made 34 contributions across 11 projects. This extensive experience on the platform has allowed me to develop a keen understanding of delivering high-quality solutions under tight deadlines.
Due to my web2 experience, i am skilled in writing Typescript and i  would love to contribute to this project by solving this issue.
Below is a link to my OnlyDust public profile.
https://app.onlydust.com/u/Dprof-in-tech


### How I plan on tackling this issue
To solve this issue, i would:

Update TypeScript: I'll install the latest stable version of TypeScript and ensure it's reflected in the project dependencies.

Verify the Version: I’ll confirm that the latest version is installed and working correctly.

Review Changes: I’ll check the release notes for any updates or breaking changes and ensure that our code is compatible with the new version.

Update Configuration: If needed, I’ll adjust the TypeScript configuration file to align with the latest standards and features.

Test Everything: I’ll run a full test of the codebase to catch any issues, making sure our project builds correctly and functions as expected.

Fix and Optimize: If any issues arise due to the upgrade, I’ll resolve them and take advantage of new features to optimize our code where possible.

Commit the Changes: Once everything is tested and working, I’ll commit the updates for future use.

This process will ensure that we’re using the latest version of TypeScript, keeping the project up-to-date and taking advantage of the latest improvements

**Comment by Ugo-X** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stellar-cli).

### My background and how it can be leveraged
 

I am a Full Stack blockchain Developer with expertise in Next.js, Nest.js, TypeScript, JavaScript, React, Node.js, Three.js, Solidity and rust. My journey with OnlyDust hackathons began at Edition 1, and I've since made 69 contributions across 14 projects. With my extensive experience on the OnlyDust platform (profile:  https://app.onlydust.com/u/Ugo-X), I've honed my skills in delivering quality solutions under pressure. 

I bring a unique blend of technical proficiency and user-focused design to every project, whether it's crafting immersive 3D experiences or developing smart contracts. My track record shows I can adapt quickly and contribute effectively to diverse challenges. 

As we surf through Edition 8, I'm excited to leverage my skills and hackathon experience to push the boundaries of blockchain development. I'm confident in my ability to tackle new challenges and drive innovation in this space.

### How I plan on tackling this issue
I will update the TypeScript version in the project. 

  

- **Step 1:** I will check the current version of TypeScript used in the project by examining the `package.json` file. 

  

- **Step 2:** I will visit the TypeScript npm page to identify the latest stable version available. 

  

- **Step 3:** I will update the `package.json` to reflect the new version and run the appropriate commands to install the updated package. 

  

- **Step 4:** I will run tests to ensure that the upgrade does not introduce any breaking changes. 

  

- **Step 5:** I will update the documentation to note the new TypeScript version and any relevant changes.

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stellar-cli).

### My background and how it can be leveraged

hello i am a frontend dev and blockchain developer
please can i work on this issue :) and would love to be a contributor


### How I plan on tackling this issue
this issue is easy to tackle kindly assign

**Comment by josephchimebuka** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stellar-cli).

### My background and how it can be leveraged
Hello, I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute.

### How I plan on tackling this issue
I will upgrade the packaged Typescript version to the latest and conclude in 1-2 days

**Comment by jsanchez556** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stellar-cli).

### My background and how it can be leveraged
Hello, I’m Jose Mario from Costa Rica. With over 15 years of experience in development, I am passionate about contributing to open-source projects and currently expanding my skill set with Rust, Cairo, and Solidity as part of my involvement with Dojo Coding.I am eager to apply my extensive experience and newly acquired skills to new challenges and innovative projects.

### How I plan on tackling this issue
1. Run npm init to create a new package,json file
2. Add the latest version of TypeScript from https://www.npmjs.com/package/typescript?activeTab=versions under devDependencies.
3. Run npm install to install the TypeScript package.
4. Test the project to ensure compatibility, as there might be breaking changes between versions.
5. Update any necessary configs on tsconfig.json

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stellar-cli).

### My background and how it can be leveraged
I am a Full Stack Developer with extensive experience in blockchain development, specializing in Next.js, TypeScript, Node.js, and Rust. With over 18 contributions across projects in the OnlyDust ecosystem, I’ve developed a strong proficiency in delivering high-quality solutions and tackling complex issues under tight deadlines. My experience spans frontend, backend, smart contract development, and a deep understanding of optimizing and maintaining scalable codebases.

### How I plan on tackling this issue
To approach this upgrade, I will start by reviewing the entire codebase and its dependencies to identify any potential conflicts with the new TypeScript version. Once the assessment is done, I’ll upgrade TypeScript to the latest stable release, ensuring all configurations, particularly in the tsconfig.json file, are updated accordingly.

After upgrading, I will run tests to identify any type errors that may arise from the new version, refactoring the code where necessary to maintain type safety. I’ll then run both unit and integration tests, combined with manual testing, to validate that everything is working as expected. Any updates required for tools like ESLint or Prettier will also be addressed to maintain the developer experience.

Lastly, I’ll ensure that performance remains unaffected by the upgrade and prepare everything for deployment. This update will keep the project current, enhance type-checking, and improve security, all while maintaining stability and ensuring a smooth transition for the team.

**Comment by pheobeayo** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stellar-cli).

### My background and how it can be leveraged
I am Web3 frontend developer skilled in Cairo, Typescript, JavaScript, Cairo, and Solidity. 
I have successfully contributed to an open source project like starknet quest

### How I plan on tackling this issue
- I will check the present typescript package
- I will upgrade to the latest one recommended aligning all functions without errors and  bugs
- fix all bugs
- Create a PR
- Ask for a Review
- Update changes made

**Comment by t0fudev** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stellar-cli).

### My background and how it can be leveraged
Helloo, my name is Hellen. I´m currently a computer science student and a web3 developer. I have been working on different exercises on different platforms like Exercism and Starklings in the past weeks so I can get my knowledge about the different languages better . I am hopeful to contribute on this repository!!

### How I plan on tackling this issue
I would work on this problem by doing the following:

- Checking carefully the project to see the current TypeScript version.
- Installing the latest version of TypeScript taking into account the dependencies of the project.
- Then, checking that the installed version is going to be compatible 
- Test and fix any errors presented if it is showed until it works perfectly.

**Comment by sasasamaes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stellar-cli).

### My background and how it can be leveraged
JavaScript developer with 5+ years of experience involved in the full software development lifecycle. My experience includes providing IT solutions for enterprises using JavaScript, React, TypeScript, Node.js, and MongoDB. Additionally, I am expanding my knowledge in Web3 technologies, particularly in Cairo and Solidity.

I am also a community leader and sensei at Dev.f, where I mentor and lead a vibrant community of developers and am a Dojo Coding Member.

My areas of interest include Web3, frontend, backend, and full-stack development.

### How I plan on tackling this issue
First I position myself in the terminal in each of the projects of the typescript package
npm i
npm list typescript
to know which version was installed
npm install typescript@latest --save-dev
to update it to the latest version
Test the project
npm run build
to check that it compiles

**Comment by Luluameh** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stellar-cli).

### My background and how it can be leveraged
I have experience in TypeScript and JavaScript development, with a focus on package management and dependency updates. I’ve previously worked on similar upgrades to ensure compatibility and leverage new features.

### How I plan on tackling this issue
I’d start by reviewing the current TypeScript version in the project and checking the changelog for breaking changes. Then, I’d upgrade to the latest version, run tests to ensure compatibility, and address any issues that arise during the update process.

**Comment by Benjtalkshow** [comment]
Hello, @piyalbasu , i will make a PR soon. There has been a huge progress.

**Comment by Benjtalkshow** [comment]
@piyalbasu 
I just updated my PR #1641

**Comment by Benjtalkshow** [comment]
@willemneal please help review my PR. Thanks
