### ISSUE TITLE
Allow installing without specifying the `soroban-cli` as the name

### ISSUE THREAD

**Issue by kalepail** [stellar/stellar-cli#1205]
```
% cargo install --git https://github.com/stellar/soroban-cli --features opt 
    Updating git repository `https://github.com/stellar/soroban-cli`
error: multiple packages with binaries found: soroban-cli, soroban-hello. When installing a git repository, cargo will always search the entire repo for any Cargo.toml.
Please specify a package, e.g. `cargo install --git https://github.com/stellar/soroban-cli soroban-cli`.
```

**Comment by janewang** [comment]
What's the goal for this? Just to not have to input the name?

**Comment by kalepail** [comment]
as I understand it it’s leftover from when the rpc and cli were bundled

**Comment by leighmcculloch** [comment]
I'm also unclear on what the goal is. You can specify either `soroban-cli` or `stellar-cli` as the name. It's common to specify the crate name when using `cargo install` because that's what you do when installing from crates.io as well. The fact that it works without the name when specifying a git source is an edge case that I don't see commonly used.

Use either of the following commands and both the `stellar` and `soroban` binaries should be installed locally. We shouldn't need to change anything for people to install from source.

```
cargo install --locked soroban-cli --git https://github.com/stellar/soroban-cli
```

or

```
cargo install --locked stellar-cli --git https://github.com/stellar/stellar-cli
```

I'd like us to support publishing both crates and both binaries for an indefinite amount of time.

I'm going to close this because it seems like it's working as expected, but please reopen / comment if we're missing something.
