### ISSUE TITLE
network: Add `--preset PRESET` to `soroban config network add`

### ISSUE THREAD

**Issue by fnando** [stellar/stellar-cli#1254]
### What problem does your feature solve?

Make adding testnet and futurenet network config easier. This would simplify the getting started docs.

### What would you like to see?

A `--preset PRESET` switch that supersedes `--rc-url` and `--network-passphrase`, where `PRESET` can be either `testnet` or `futurenet`.

### What alternatives are there?

Setting the configuration manually.

**Comment by willemneal** [comment]
I have wanted this for a while. The issue is that for public networks it is tricky because it is unclear which URL we should provide when there are multiple RPC providers.  One idea I've had is to provide a list and have users pick or randomly pick one for them.

**Comment by fnando** [comment]
@willemneal my idea is to avoid doing the following during setup phase of the Getting Started guide:

```
soroban network add --global testnet \
  --rpc-url https://soroban-testnet.stellar.org:443 \
  --network-passphrase "Test SDF Network ; September 2015"
```

So if you choose to use `--preset testnet`, the above will always be used. The of that network can be whatever you want, so I don't think it'd be a conflict with multiple RPC providers.

Does that make sense? Maybe I need to understand the multiple RPC provider thing a little bit better too.

**Comment by willemneal** [comment]
Different RPC providers provide other rpc-url's to choose from. If we go with this route all users will go through the same one. But we already use this in the docs so perhaps it's best to just use this for now.

**Comment by leighmcculloch** [comment]
This is convenient, but even locally may be challenging. I might want to add a testnet RPC, but that testnet RPC might be local, remote. And folks will definitely need to add a URL for pubnet, so I guess the question is do we get enough benefit out of this for testnet alone.

And can we get this benefit another way, such as including a default `testnet` network that is always configured with the above? A default would address the one use case, whilst not complicating the CLI further.

**Comment by leighmcculloch** [comment]
Another option is we make the network passphrase optional when adding. It's possible for the CLI to request the network passphrase from the RPC. 

We leaned away from this in the past because someone could be exploited to sign txns for pubnet when they mean to be using testnet. But we could also do some things to prevent this, such as:
- outputting to stderr what passphrase is being used
- requiring that pubnet's passphrase always be explicitly provided. If a network is added without the passphrase, and the rpc lookup returns the pubnet passphrase, simply throwing an error, telling the user that when adding the pubnet network the passphrase must be explicitly provided

This would reduce the commands for dev/testing to:

```
$ soroban network add testnet --rpc-url https://soroban-testnet.stellar.org:443
```

**Comment by leighmcculloch** [comment]
Presets basically exist with defaults now.
