### ISSUE TITLE
Defaults for global config

### ISSUE THREAD

**Issue by JakeUrban** [stellar/stellar-cli#1396]
### What problem does your feature solve?

If you are using a local project-based config `.soroban` directory, you can set environment variables in a `.env` file that specify the network and source account that should be used if omitted from a command.

note: being able to set these environment variables is undocumented other than in the `--help` message for some commands

However, if you're using global config, you have to set the environment variables in your shell.

### What would you like to see?

It would be great if I could configure which network and source account to use via a `use` command or something similar.

```bash
stellar network add testnet --rpc-url ... --network-passphrase ...
stellar network use testnet
stellar keys generate primary  # no --network flag needed
stellar keys use primary
stellar contract id asset --asset native  # no --network or --source-account flags needed
```

### What alternatives are there?

Using environment variables.

**Comment by willemneal** [comment]
Great idea! We are planning on refactoring the config so that you could for example take advantage of the network you are compiling to so you could get the id of the native SAC like in your final example. I had been wondering how you would handle checking which network is currently in use when compiling and this seems like a good way to handle it.

**Comment by leighmcculloch** [comment]
It would be helpful if we add a command that shows you the current state, based off all the inputs that can affect state such as env vars, the `use` commands, etc.

I think we need to explore a bit to what that could look like, but as an example:

```
$ export STELLAR_NETWORK=testnet
$ stellar keys use primary
$ stellar config
network=testnet (env)
key=primary (use)
```

**Comment by leighmcculloch** [comment]
> ```
> $ export STELLAR_NETWORK=testnet
> $ stellar keys use primary
> $ stellar env
> network=testnet (env)
> key=primary (use)
> ```

Floating this idea: think we should make this operate around env vars, since every config has an env var, instead of mapping to some third concept (the `network`, `key` above).

This is something other tools like `go env` do:

```
$ export STELLAR_NETWORK=testnet
$ stellar keys use primary
$ stellar env
STELLAR_NETWORK=testnet # env
STELLAR_ACCOUNT=primary # env
```

We can still add annotations, except use `#` so it's a comment.

If you want to save the current env in a .env file, it's essentially `stellar env > .env`. If we're planning to get rid of the local .stellar folder, this may play into a story that folks use for project based config.

**Comment by leighmcculloch** [comment]
Or, instead of `stellar env` outputting the env variables, have `stellar config` output what the effective config in TOML format. Someone else suggested this (@fnando maybe?), I'm just repeating the idea, and map any option that has an env var back to a config entry, so there's this clear mapping of:

```mermaid
flowchart LR
    T(TOML) <--> E(Env)
    E(Env) <--> O(Option)
    T(TOML) <--> O(Option)
    Te(network) <--> Ee(STELLAR_NETWORK)
    Ee(STELLAR_NETWORK) <--> Oe("--network")
    Te(network) <--> Oe("--network")
```

**Comment by fnando** [comment]
@leighmcculloch I love the idea of outputting .env/shell output.

In this example, the correct output would be something like this, right? Notice the source for `STELLAR_ACCCOUNT`.

```console
$ export STELLAR_NETWORK=testnet
$ stellar keys use primary
$ stellar env
STELLAR_NETWORK=testnet # env
STELLAR_ACCOUNT=primary # default
```

What should the output be when no values are set (no env var, or `use`)?

**Comment by fnando** [comment]
@leighmcculloch implemented it here: https://github.com/stellar/stellar-cli/pull/1690/files#diff-0188aa8b2b7f1c628848fd93f5745da20904ecc2dad8f456336c47776a74d95eR901

**Comment by leighmcculloch** [comment]
I believe this was resolved by 👆🏻
