### ISSUE TITLE
Emulator tests still flakey

### ISSUE THREAD

**Issue by willemneal** [stellar/stellar-cli#1461]
Currently main has been running the emulator test for more than 2 hours https://github.com/stellar/stellar-cli/actions/runs/9958635740/job/27513514323

And other PRs are still experience failing tests.

**Comment by janewang** [comment]
+1 The emulator tests are still failing on various PRs

**Comment by Ifropc** [comment]
Checked on this test failures locally, it looks like docker is the reason this tests are unstable... Though there are some other weird issues (e.g. there are a lot of ports allocated to the container, and I don't think all of them are used. There are 2 tcp and 2 udp mapping for the same port, which is weird. Issues connecting to the UI seems to be caused by wrong port used) 
Might be worth looking into auto-restarting docker if it's unhealthy

**Comment by elizabethengelman** [comment]
Thanks for looking into this @Ifropc!

That's a great call that a lot of the ports are allocated aren't used, and there are TCP and UDP mappings for the same port. I had forgotten about both of those things. Definitely seems like its worth trying to clean those things up.

**Comment by elizabethengelman** [comment]
Also just to confirm i'm reading your message correctly @Ifropc were you able to replicate these failures locally on your machine?

**Comment by Ifropc** [comment]
Yes, when you run the test enough times it fails. I also got some failures because of incorrect port mappings (they seem to be random and doesn't look like it affects the pipeline), which I fixed locally. 
FYI: with incorrect ports test fails to connect to the UI at the start of the test, which for me starts on one of two ports(and in code docker client can only fetch one of them, which sometimes is incorrect. Once again, not sure if it's a local issue or not). My local fix was simply trying another port if first one didn't work.
But the ledger connection issue was still present... Which I though was related to ports, but it was not after all.
Getting logs from docker image might help for debugging
If you wrap one test in `for 1 .. 100 { run_test }` it will fail (eventually)

**Comment by elizabethengelman** [comment]
> when you run the test enough times it fails
> If you wrap one test in for 1 .. 100 { run_test } it will fail (eventually)

Great call, I'm seeing that now locally as well!

I think that what you were seeing was the issue where when we were publishing all of the ports, it seemed that there was some conflict between containers and if the ports were available. Which is weird. But, I was able to publish just the ports we need. Going to open a PR for this shortly and would love your eyes on it!
