### ISSUE TITLE
error: unexpected contract code got token on Contract addresses

### ISSUE THREAD

**Issue by OlegJakushkin** [stellar/stellar-cli#1488]
### What version are you using?
```
C:\Users\olegj\.cargo\bin\stellar.exe -V    
stellar 21.2.0 (622c9915ac8c9645e53fe64cf5df73283630ff15)
soroban-env 21.2.0 (8809852dcf8489f99407a5ceac12625ee3d14693)
soroban-env interface version 90194313216
stellar-xdr 21.2.0 (9bea881f2057e412fdbb98875841626bf77b4b88)
xdr curr (70180d5e8d9caee9e8645ed8a38c36a8cf403cd9)
```

### What did you do?
```
C:\Users\olegj\.cargo\bin\stellar.exe contract fetch 
 --rpc-url https://docs-demo.stellar-mainnet.quiknode.pro/ --network-passphrase 
"Public Global Stellar Network ; September 2015" --id CBBJTE34KZHJACB2A6OXCRTDDLX4LI7GKYYD6XYJSGMX46BLNAG752HS
error: unexpected contract code got token
```
Same for `CAUIKL3IYGMERDRUN6YSCLWVAKIFG5Q4YJHUKM4S4NJZQIA3BAS6OJPK` and `CDCKFBZYF2AQCSM3JOF2ZM27O3Y6AJAI4OTCQKAFNZ3FHBYUTFOKICIY` and other popular contract assets

### What did you expect to see?
Contract wasm file

### What did you see instead?
```
error: unexpected contract code got token
```

**Comment by willemneal** [comment]
These are built contracts. What are you trying to do?

**Comment by OlegJakushkin** [comment]
@willemneal Get a formal process where, for any contract address, I could:
1) Get its wasm file
2) Inspect (using `soroban.exe contract inspect`) its functions
3) Get the ability to present to my users how that contract can be used and what of its variables can be read.
4) Call and inspect any contract from my web UI

**Comment by leighmcculloch** [comment]
@OlegJakushkin on Soroban there are built-in contracts which aren't WASM files, and then WASM files. The built-in contracts are contracts provided by the network. The contract `CBBJ...` you referenced is a stellar asset contract and that's why you're unable to download it.

The error message is not very clear and we should improve it. Let's use this issue to track improving that error message to something like:

```
error: cannot fetch wasm for contract CBBJ... because the contract is a network built-in contract that does not have a downloadable code binary
```

Note that it appears the logic for where the error is defined is in the stellar-rpc-client, so addressing this issue shuold involve moving that logic from the stellar-rpc-client to the stellar-cli. This should be code that lives in the CLI. The rpc client should just expose a get ledger entry function, and the CLI should use that function to fetch the contract and then the wasm if it exists. The client doesn't need to own the logic, and by doing so it is a tight coupling of CLI behavior with the rpc client. I'll open an issue

**Comment by OlegJakushkin** [comment]
Dear @leighmcculloch, ok, so how can one view such "built-in contracts" API info, and what other types of such contracts are there?

**Comment by Ifropc** [comment]
@leighmcculloch I can take this issue on on both cli and rpc-client
@OlegJakushkin There are just 2 types, as mentioned above by Leigh. You can read more on Stellar Asset contracts [here](https://developers.stellar.org/docs/tokens/stellar-asset-contract) (this is the type of contracts that you encountered)

**Comment by OlegJakushkin** [comment]
Thank you very much!

**Comment by OlegJakushkin** [comment]
Dear @Ifropc where one could find SDK reference implementations in the form of WASM files for that standard token asset ([CAP-46-6 Smart Contract Standardized Asset](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0046-06.md) and [SEP-41 Token Interface](https://developers.stellar.org/docs/tokens/token-interface))?

**Comment by Ifropc** [comment]
Hi @OlegJakushkin native contracts don't have WASM files. The links you provided contains the interface asset contract implements

**Comment by OlegJakushkin** [comment]
Dear @Ifropc, so, how to get their API in the same form `soroban.exe contract inspect` gives for other contracts?

**Comment by Ifropc** [comment]
@OlegJakushkin you are right, currently there aren't a clear way to do so. I talked internally with @leighmcculloch and I propose a new command that will cover this use case, and (potentially) improve the current `inspect` command's usability.
Tracking issue: https://github.com/stellar/stellar-cli/issues/1506
