### ISSUE TITLE
Change the default to not `npm build`

### ISSUE THREAD

**Issue by chadoh** [stellar/stellar-cli#1512]
### What problem does your feature solve?

Some pro users don't want to use our TS Bindings because a whole NPM package feels too heavy.

### What would you like to see?

Let's add a `--file-only` option to the `bindings typescript` command that will:

- honor the `--output-dir` option, and emit only `[output-dir]/index.ts` (NOT `[output-dir]/src/index.ts`)
- output a message to stdout (or stderr, whatever the rest of the file is doing) saying:
  
  ```
   Created [output-dir]/index.ts. NOTE: You must have an NPM project configured with:

    - typescript@[version from template's package.json] or compatible version
    - @stellar/stellar-sdk@[version from template's package.json] or compatible version
    - buffer@[version from template's package.json] or compatible version
   ```

Print that you need node and npm installed 

### What alternatives are there?

Don't

**Comment by leighmcculloch** [comment]
I'm not sure the bindings generate command should output an incomplete view of the generated bindings. The bindings generated are dependent on a specific version of the js-stellar-sdk and other dependencies, and so outputting an incomplete bundle seems like it would set folks up for failure.

I'd like to understand what the specific inconvenience is. For folks who don't want the whole NPM package they can generate the bindings and copy out the `index.ts` file and discard the rest, so the workflow described in the issue is already supported.

Is that the inconvenient piece of the existing workflow doing a `cp index.ts newlocation` out of the bundle?

Or is the inconvenient piece that bindings call `npm install` or `npm whateveritdoes`?

If it's the latter, then I think it'd make sense to add an option to skip the npm install.

**Comment by janewang** [comment]
Copying out the `index.ts` suffices the user case. The CLI doesn't need another flag to just help user remove some files.

**Comment by leighmcculloch** [comment]
> --no-build

👍🏻

**Comment by janewang** [comment]
After discussion, we agreed to changing the default behavior to not build. We will not add any flags.

**Comment by leighmcculloch** [comment]
> changing the default behavior to not build

Part of the reason was that someone pointed out that in other ecosystems like solidity the code gen just generates files and it's up to the user to run npm commands.

Given that it is easy to call `&& npm ...` after codegen that seems like a reasonable default.

**Comment by leighmcculloch** [comment]
> ```
> Created [output-dir]/index.ts. NOTE: You must have an NPM project configured with:
> 
>   - typescript@[version from template's package.json] or compatible version
>   - @stellar/stellar-sdk@[version from template's package.json] or compatible version
>   - buffer@[version from template's package.json] or compatible version
> ```

+1 When removing the calls to npm it's pretty important we educate the user on what got generated and what they need to do to use it, so it's pretty critical we include output like this.

**Comment by leighmcculloch** [comment]
I've opened two PRs relating to this issue, and the area of code it refers:
- https://github.com/stellar/stellar-cli/pull/1731
- https://github.com/stellar/stellar-cli/pull/1733
