### ISSUE TITLE
Aliases should be visible in the auto generated markdown

### ISSUE THREAD

**Issue by willemneal** [stellar/stellar-cli#1545]
Also the alias should be visible in the markdown so this seems like a bug.

_Originally posted by @willemneal in https://github.com/stellar/stellar-cli/pull/1406#discussion_r1715856681_

**Comment by janewang** [comment]
Clap markdown bug. we should open an issue on the clap reop @willemneal

**Comment by leighmcculloch** [comment]
This issue has already been requested on the clap-markdown repository:
- https://github.com/ConnorGray/clap-markdown/issues/32

**Comment by thesledge04** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stellar-cli).

### My background and how it can be leveraged
I have experience in software development, particularly with solidity and Rust, and I am familiar with GitHub workflows. My background enables me to efficiently identify and fix bugs in code while ensuring adherence to best practices and user needs.

### How I plan on tackling this issue
Review the code to locate alias processing.
Identify the rendering issue for the alias.
Modify the logic to include the alias in Markdown.
Test the changes to ensure correct output.
Document the fix for clarity.

**Comment by josephchimebuka** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stellar-cli).

### My background and how it can be leveraged
Hello, I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. 

### How I plan on tackling this issue
I would like to fix this

**Comment by devcollinss** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stellar-cli).

### My background and how it can be leveraged
My name is Collins Ikechukwu. I'm a full stack blockchain developer developer.

### How I plan on tackling this issue
### Steps to Implement:

1. **Identify the Issue Context**
   - Review the PR referenced [here](https://github.com/stellar/stellar-cli/pull/1406#discussion_r1715856681) to understand the alias visibility issue in markdown.
   - Confirm how the alias is currently being rendered and why it may not be displaying as expected.

2. **Check Markdown Syntax**
   - Ensure that the alias is correctly formatted in the markdown file. Aliases should be displayed using proper syntax (backticks for inline code or fenced code blocks if necessary):
     ```markdown
     `alias_name`
     ```
   - Verify that the markdown parser being used for the documentation supports the correct rendering of aliases.

3. **Debug the Rendering Bug**
   - Investigate if there is an issue with the markdown rendering engine or the way the markdown is being generated.
   - Check for potential conflicts in the markdown parser configuration that could be causing the alias to not appear or display incorrectly.

4. **Test and Validate**
   - After making adjustments, test the markdown rendering locally to ensure the alias is now visible and displayed as intended.
   - If this is part of an automated documentation generation process, ensure that the alias appears correctly in the final rendered output.

5. **Review and Submit Fix**
   - Once the issue is resolved, document the fix and submit a PR, referencing the original discussion to confirm the resolution of the bug.

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stellar-cli).

### My background and how it can be leveraged
I have extensive experience working with various technologies, particularly in improving developer tooling and workflows. Having contributed to multiple projects within the OnlyDust ecosystem, I understand the importance of clean and efficient code, as well as maintaining clarity in documentation.

### How I plan on tackling this issue
The issue at hand involves ensuring that aliases are visible in the auto-generated markdown files. Currently, these aliases are not being rendered, which creates a lack of clarity in the documentation. This seems like a bug, as the alias should be part of the output.

To tackle this, I will first review the auto-generation logic to identify where the alias data is being missed or incorrectly handled. I’ll ensure that the aliases are correctly parsed and included during the markdown generation process. Once the issue is located, I’ll modify the script or configuration responsible for generating the markdown to include aliases.

After implementing the fix, I will regenerate the markdown and run tests to confirm that the aliases appear as expected. I’ll also ensure that the new behavior is consistent across all areas of the project, providing clear and complete documentation for users and developers. This fix will enhance the readability and usability of the generated markdown, ensuring a smoother developer experience.

**Comment by Luluameh** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/stellar-cli).

### My background and how it can be leveraged
I have experience working with TypeScript, JavaScript, and Rust, particularly in debugging and enhancing CLI tools. I’ve worked on generating documentation and ensuring important details, such as aliases, are correctly reflected.

### How I plan on tackling this issue
I’d start by analyzing the markdown generation logic to identify why aliases are missing. I’d then adjust the markdown generator to ensure aliases are included where needed, testing the changes to confirm that the issue is resolved across various use cases.

**Comment by janewang** [comment]
https://github.com/stellar/stellar-cli/pull/1649/files

**Comment by janewang** [comment]
We will make an issue upstream
