### ISSUE TITLE
Support contract aliases in caller arguments

### ISSUE THREAD

**Issue by Ifropc** [stellar/stellar-cli#1764]
### What problem does your feature solve?

When using contract aliases they can't be used in contract arguments (see example)

```bash
[ /tmp/soroban-project ] > echo $MAIN_CONTRACT 
CB4RERBQMEEXGUFPRZDIN46WTMETHR6EMTWRWXIZO6Q3527GTZI3EK7U
[ /tmp/soroban-project ] > echo $ADD_CONTRACT
CCXZXWJ4FXPEG2453SOYSU5BHCVXSAGDJX63TGNCM6KTCOFJ2KJUTQKF
[ /tmp/soroban-project ] > stellar contract alias ls
ℹ️ Aliases available for network 'Test SDF Network ; September 2015'
test_add_contract: CCXZXWJ4FXPEG2453SOYSU5BHCVXSAGDJX63TGNCM6KTCOFJ2KJUTQKF
test_main: CB4RERBQMEEXGUFPRZDIN46WTMETHR6EMTWRWXIZO6Q3527GTZI3EK7U
[ /tmp/soroban-project ] > stellar contract invoke --id $MAIN_CONTRACT --network testnet -- add_with --contract $ADD_CONTRACT --x 9 --y 10
ℹ️ Send skipped because simulation identified as read-only. Send by rerunning with `--send=yes`.
19
[ /tmp/soroban-project ] > stellar contract invoke --id test_main --network testnet -- add_with --contract $ADD_CONTRACT --x 9 --y 10 
ℹ️ Send skipped because simulation identified as read-only. Send by rerunning with `--send=yes`.
19
[ /tmp/soroban-project ] > stellar contract invoke --id test_main --network testnet -- add_with --contract test_add_contract --x 9 --y 10
❌ error: parsing argument contract: value is not parseable to Some(
    Address,
)
```

As a result, it's required to pass contract id as an env variable or just string

### What would you like to see?

CLI to be able to convert contract alias to Address internally when calling contracts 

### What alternatives are there?

Using env variables

**Comment by estherbreath** [comment]
### I would like to work on this issue, please

Here are clues on how I intend to go about it:

1. Implement a feature in the CLI to automatically convert contract aliases to addresses when invoking functions.
2. Add a new internal conversion function that takes an alias and returns the corresponding full address.
3. Modify the contract invocation logic to use this conversion function for alias inputs.
4. Update the CLI's argument parsing to recognize both full addresses and aliases.
5. This change will simplify usage, allowing developers to work with familiar alias names instead of full addresses throughout their workflow.
